### ISSUE TITLE
Some notes

### ISSUE THREAD

**Issue by kentcdodds** [threepointone/markdown-in-js#1]
Hey man, this looks spectacular and I'll probably use it. Just thought I'd note a few things that I noticed:

In the README.md it says

> add `'markdown-in-js/lib/babel'` to the plugins field of your `babel` config

But in `src/index.js` [the error](https://github.com/threepointone/markdown-in-js/blob/2283100122fad905d6c7adebe2828449bff76e43/src/index.js#L2) you're throwing says:

> you forgot to add `'markdown-in-js/babel'` to your babel plugins

I think that the README is correct, but I'm not sure so I thought I'd bring it up :smile:

Also, I noticed that in your example [here](https://github.com/threepointone/markdown-in-js/blob/2283100122fad905d6c7adebe2828449bff76e43/examples/index.js#L4) you have:

> import markdown from '../src' // so the linter won't complain

Which makes sense, I imagine that this isn't required at all by the plugin, but I'll bet that others may want to do the same and be unsure of what to do. Perhaps in the README we could mention that in the usage?

**Comment by threepointone** [comment]
Good catches, I missed it when making the initial release and moving stuff around. I also might end up needing to import a function anyway, to do stuff like custom components etc. I'll get the changes into the README soon.

**Comment by kentcdodds** [comment]
Thanks again for building awesome stuff :)

**Comment by threepointone** [comment]
The feeling's mutual!

**Comment by threepointone** [comment]
fixed in https://github.com/threepointone/markdown-in-js/commit/a130f431de7fb7de304121c704ed93e5945b5fe7, closing.

**Comment by threepointone** [comment]
heads up, the import is now mandatory, and we now have support for custom components.
