### ISSUE TITLE
External files

### ISSUE THREAD

**Issue by angamaiton** [threepointone/markdown-in-js#9]
Hey! If I've missed this somewhere, I'm sorry, but is there a way to use this plugin to support an external .md file?

I'm trying to do something like this:

```
import React from 'react'
import md from 'markdown-in-js'
import aboutPage from '../docs/about.md'

export default () => (
  <div className="entries">
    { md`${aboutPage}` }
  </div>

)
```

**Comment by kennetpostigo** [comment]
This is something I think is better than strings and would definitely use.

**Comment by threepointone** [comment]
Not in the scope of this library, you're better off using a markdown loader/ shipping a parser to the browser if you want this. Closing.
